import React, { useState } from "react";
import {
  View,
  StyleSheet,
  Text,
  FlatList,
  TouchableOpacity,
} from "react-native";
import { globalStyles } from "../styles/global";

export default function UserWeek({ navigation }) {
  const [weekDays, setWeekDays] = useState([
    {
      day: "Sunday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "0",
    },
    {
      day: "Monday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "1",
    },
    {
      day: "Tuesday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "2",
    },
    {
      day: "Wednesday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "3",
    },
    {
      day: "Thursday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "4",
    },
    {
      day: "Friday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "5",
    },
    {
      day: "Saturday",
      freeTimes: [
        { time: "", color: "white", key: "0" },
        { time: "1 AM", color: "white", key: "1" },
        { time: "2 AM", color: "white", key: "2" },
        { time: "3 AM", color: "white", key: "3" },
        { time: "4 AM", color: "white", key: "4" },
        { time: "5 AM", color: "white", key: "5" },
        { time: "6 AM", color: "white", key: "6" },
        { time: "7 AM", color: "white", key: "7" },
        { time: "8 AM", color: "white", key: "8" },
        { time: "9 AM", color: "white", key: "9" },
        { time: "10 AM", color: "white", key: "10" },
        { time: "11 AM", color: "white", key: "11" },
        { time: "12 PM", color: "white", key: "12" },
        { time: "1 PM", color: "white", key: "13" },
        { time: "2 PM", color: "white", key: "14" },
        { time: "3 PM", color: "white", key: "15" },
        { time: "4 PM", color: "white", key: "16" },
        { time: "5 PM", color: "white", key: "17" },
        { time: "6 PM", color: "white", key: "18" },
        { time: "7 PM", color: "white", key: "19" },
        { time: "8 PM", color: "white", key: "20" },
        { time: "9 PM", color: "white", key: "21" },
        { time: "10 PM", color: "white", key: "22" },
        { time: "11 PM", color: "white", key: "23" },
        { time: "", color: "white", key: "24" },
      ],
      key: "6",
    },
  ]);

  const newWeekDays = [];

  return (
    <View style={globalStyles.container}>
      <View style={styles.userWeekContainer}>
        <View style={styles.listContainer}>
          <FlatList
            data={weekDays}
            extraData={newWeekDays}
            renderItem={({ item }) => (
              <TouchableOpacity
                onPress={() => navigation.navigate("UserTimes", item)}
              >
                <View style={styles.dayContainer}>
                  <Text style={styles.days}>{item.day}</Text>
                </View>
              </TouchableOpacity>
            )}
          />
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  userWeekContainer: {
    backgroundColor: "white",
    borderColor: "#00AAFF",
    borderWidth: 1.5,
    borderRadius: 5,
    margin: 0,
    padding: 10,
    width: "43%",
    height: "100%",
  },

  listContainer: {
    flex: 1,
  },

  dayContainer: {
    flex: 1,
    justifyContent: "space-around",
    backgroundColor: "white",
    borderColor: "#00AAFF",
    borderWidth: 1.5,
    borderRadius: 5,
    elevation: 3,
    shadowOffset: { width: 1, height: 1 },
    shadowColor: "#333",
    shadowOpacity: 0.3,
    shadowRadius: 2,
    margin: 3,
    paddingTop: 19,
    paddingBottom: 19,
  },

  days: {
    color: "black",
    textAlign: "center",
  },
});
